게시판 관련 기능 구현
FitToMe/FTM-server pull request #5
Opened 2022-05-30 04:22 UTC by jinyoung-2

2022-07-14 08:23 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Entity/Post/PostEntity.java
> +        // Q. User 객체에 대한 정보는 안 넣어줘도 되나?
넣어줘야죠,  하지만 아직 인증 기능이 구현이 안되어있기 때문에 추후에 제가 인증부분 구현하면서 추가하겠습니다.

2022-07-14 08:33 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Request/PostRequest.java
> +import javax.validation.constraints.NotBlank;
validation을 사용하려면 `build.gradle`에 `
    implementation 'org.springframework.boot:spring-boot-starter-validation'` 의존성을 추가해줘야합니다.

아마 commit할때 빠뜨린게 아닌가 싶어요

2022-07-14 08:39 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Controller/PostController.java
> +    PostStatusService postStatusService;
`@RequiredArgsConstructor`는 초기화 되지않은 final 필드나, `@NonNull` 이 붙은 필드에 대해 생성자를 생성해 주기 때문에 이 어노테이션을 사용해서 의존성 주입을 하는 경우 해당 필드에 `final`을 붙여주어야 합니다. 

그리고 외부에서 controller를 통해 service객체에 직접 접근하는 것이 바람직하지 못하므로 `private` 접근지정자를 붙여주는게 좋을 것 같습니다.

2022-07-14 08:43 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Repository/PostRepository.java
> +    Optional<PostEntity> findAllTitle(String postTitle); //check
JPA는 메서드 이름을 기준으로 자동으로 query를 생성해주기 때문에 해당 메서드의 이름을 `findAllByTitle`로 해줘야 합니다.

해당 메서드 이름을 그대로 사용하고 싶다면 `@Query` 어노테이션을 통해 직접 query문을 작성해서 사용하는 방법도 있습니다.

https://sundries-in-myidea.tistory.com/91

2022-07-14 08:50 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostRegisterService.java
> +        if(!postEntity.isPresent()){    // 존재하지 않은 경우 entity 생성
```java
if(postEntity.isPresent()) throw new IllegalArgumentException("해당 게사판 이름은 이미 존재합니다!");
        
        return new PostDTO(postRepository.save(PostEntity.builder()
                .title(postRequest.getTitle())
                .content(postRequest.getContent())
                .imageURL(postRequest.getImageURL())
                .build()));
```

이런 식으로 작성하면 코드가 더 깔끔해질 것 같습니다.

2022-07-14 13:02 UTC, chisan01 commented on src/main/java/com/FitToMe/project/DTO/PostDTO.java
> +    //// Q. Date의 경우 자동업데이트되는데, DTO의 변수로 작성되어야하는게 맞을까요?
약간 말이 잘 이해가 안되는데 자동업데이트 여부와는 별개로 클라이언트 쪽에서 작성날짜나 수정된날짜를 확인하고 싶다면 DTO에 포함되어야 하는게 아닐까요?

2022-07-14 13:21 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Controller/PostController.java
> +    public ApiResult<PostDTO> updatePost(@Valid @RequestBody PostRequest postRequest){
`/{post_id}`처럼 path 변수를 사용하고 싶다면 해당 메소드의 파라미터로 `@PathVariable`을 명시해주어야 합니다.

예시) `public ApiResult<PostDTO> updatePost(@PathVariable(name = "post_id") Long postId, @Valid @RequestBody PostRequest postRequest) {`

2022-07-14 14:06 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostModifyService.java
> +            throw new IllegalArgumentException("해당 게사판은 존재하지 않습니다");
이렇게 에러가 발생하는 경우 현재는 `501 Internal Server Error`로 묶여서 처리되기 때문에 `ExceptionController`를 하나 만들어서 해당 에러를 `ApiError`로 묶어서 반환하는 방식을 사용하면 좋을 것 같습니다.

https://github.com/SAMMaru5/SAMMaruServer/blob/main/src/main/java/com/sammaru5/sammaru/web/controller/exception/ExceptionController.java

2022-07-14 14:13 UTC, chisanahn requested changes
## 기타 수정사항

### `build.gradle`
`implementation 'org.springframework.boot:spring-boot-starter-security'` 의존성을 추가한뒤에 따로 security 설정을 하지 않는다면 모든 url에 접근이 허가되지 않으면서 `401 unauthroized` 오류가 발생하므로 `build.gradle`에서 제외시켜두는 것이 좋습니다.

<br>

### JPA Auditing
JPA auditing을 사용한다면 `ProjectApplication` 위에 `@EnableJpaAuditing`어노테이션을 명시해주어야 합니다.

2022-07-19 16:11 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostModifyService.java
> +        Optional<PostEntity> postEntity = postRepository.findAllTitle(postTitle);
`title`은 게시글마다 **unique** 하다는 보장이 없으므로 `title`보다는 `id`를 기준으로 `post`를 찾고 수정하는 것이 좋을 것 같습니다.

2022-07-19 16:12 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostRegisterService.java
> +        if(!postEntity.isPresent()){    // 존재하지 않은 경우 entity 생성
그리고 게시글을 수정할때 모든 항목을 수정한다는 보장이 없으므로 각각의 항목을 개별적으로 확인하고 수정하는 식으로 변경하는 것이 좋을 것 같습니다.

2022-07-19 16:17 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Entity/Post/PostEntity.java
> +public class PostEntity extends TimeEntity {
`post`의 뜻은 게시글로 혼동의 여지가 있으므로 변수명으로 대신 `board`를 사용하는 것이 더 좋을 것 같습니다.

2022-07-19 16:23 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostModifyService.java
> +            throw new IllegalArgumentException("해당 게사판은 존재하지 않습니다");
그리고 게시판이 아니라 게시글 아닌가요?

2022-07-19 16:26 UTC, chisanahn commented on src/main/java/com/FitToMe/project/Service/Post/PostModifyService.java
> +                            .build()));
게시판을 수정할때 모든 항목을 수정한다는 보장이 없으므로 각각의 항목을 개별적으로 확인하고 수정하는 식으로 변경하는 것이 좋을 것 같습니다.

2022-07-19 16:26 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostRegisterService.java
> +            throw new IllegalArgumentException("해당 게사판 이름은 이미 존재합니다!");
게시글의 경우 제목이 중복되어도 상관없지 않을까요?

2022-07-19 16:38 UTC, chisanahn commented on src/main/java/com/FitToMe/project/Request/PostRequest.java
> +    // Q. 작성자 id는 어떻게 해야할까?
`user`는 token 값을 통해 인증 후 별도로 관리하는 식으로 구현할 예정입니다.

2022-07-19 16:42 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostModifyService.java
> +                            .build()));
게시글 제목은 중복을 허용하는 것이 좋을 것 같기 때문에 수정할 게시글은 id를 기준으로 검색하는 것이 좋을 것 같습니다.

> 그리고 만약 게시글의 제목을 수정하지 않는다면 title 값은 null이 전달될 것이라는 문제도 있습니다.

2022-07-19 17:06 UTC, chisan01 commented on src/main/java/com/FitToMe/project/Service/Post/PostStatusService.java
> +        if(posts!=null){
`findAll()`의 경우 검색 결과가 없다면 빈 `List`를 리턴하므로 `null` 여부를 확인하기보다는 `isEmpty`를 사용하는 것이 더 좋을 것 같습니다.

https://stackoverflow.com/questions/35045661/spring-jpa-query-returns-null-instead-of-list

2022-07-19 17:08 UTC, chisanahn commented on src/main/java/com/FitToMe/project/Service/Post/PostStatusService.java
> +        if(posts!=null){
그리고 게시글이 없는 것을 오류로 굳이 분류하지 않고 클라이언트 쪽에서 반환받은 배열이 비어있는 경우에 별도로 처리하는 것이 더 자연스러운 것 같습니다.

2022-09-07 07:28 UTC, closed without merging